INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (1, 694.58, 'Reduz ruídos e vibrações', 'Sensor de Oxigênio');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (2, 716.86, 'Ideal para manutenção preventiva', 'Bomba de Combustível');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (3, 606.3, 'Compatível com diversos modelos', 'Retrovisor');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (4, 325.52, 'Alta eficiência de desempenho', 'Bateria');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (5, 888.94, 'Peça essencial para segurança', 'Sensor de Oxigênio');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (6, 445.79, 'Compatível com diversos modelos', 'Disco de Freio');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (7, 767.26, 'Produto novo e garantido', 'Pastilha de Freio');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (8, 371.33, 'Melhora a performance do veículo', 'Velas de Ignição');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (9, 711.24, 'Instalação fácil e rápida', 'Sensor de Oxigênio');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (10, 478.27, 'Ideal para manutenção preventiva', 'Embreagem');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (11, 647.31, 'Alta eficiência de desempenho', 'Correia Dentada');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (12, 782.79, 'Compatível com diversos modelos', 'Embreagem');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (13, 159.8, 'Peça original de alta qualidade', 'Correia Dentada');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (14, 293.49, 'Peça original de alta qualidade', 'Disco de Freio');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (15, 719.97, 'Reduz ruídos e vibrações', 'Radiador');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (16, 507.82, 'Reduz ruídos e vibrações', 'Velas de Ignição');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (17, 675.04, 'Alta eficiência de desempenho', 'Retrovisor');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (18, 515.02, 'Compatível com diversos modelos', 'Bomba de Combustível');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (19, 555.65, 'Ideal para manutenção preventiva', 'Filtro de Ar');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (20, 896.85, 'Reduz ruídos e vibrações', 'Lanterna Traseira');
