INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (1, 640.64, 'Reduz ruídos e vibrações', 'Filtro de Óleo');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (2, 547.74, 'Instalação fácil e rápida', 'Pneu');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (3, 358.88, 'Peça essencial para segurança', 'Sensor de Oxigênio');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (4, 917.97, 'Peça original de alta qualidade', 'Radiador');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (5, 637.25, 'Melhora a performance do veículo', 'Velas de Ignição');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (6, 311.25, 'Compatível com diversos modelos', 'Alternador');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (7, 414.7, 'Ideal para manutenção preventiva', 'Disco de Freio');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (8, 65.58, 'Compatível com diversos modelos', 'Farol');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (9, 830.23, 'Melhora a performance do veículo', 'Retrovisor');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (10, 937.85, 'Ideal para manutenção preventiva', 'Catalisador');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (11, 946.92, 'Resistente e durável', 'Escapamento');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (12, 248.73, 'Reduz ruídos e vibrações', 'Escapamento');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (13, 514.76, 'Alta eficiência de desempenho', 'Correia Dentada');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (14, 159.97, 'Resistente e durável', 'Lanterna Traseira');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (15, 235.39, 'Instalação fácil e rápida', 'Correia Dentada');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (16, 611.2, 'Instalação fácil e rápida', 'Bomba de Combustível');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (17, 634.03, 'Compatível com diversos modelos', 'Embreagem');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (18, 813.22, 'Peça essencial para segurança', 'Parachoque');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (19, 116.71, 'Alta eficiência de desempenho', 'Bateria');
INSERT INTO t_ps_produto (cd_produto, vl_produto, ds_produto, nm_produto) VALUES (20, 997.98, 'Alta eficiência de desempenho', 'Alternador');
