CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    telefone VARCHAR2(11) NOT NULL,
    senha VARCHAR2(100) NOT NULL
);

Select * from usuarios;

CREATE TABLE carros (
    placa VARCHAR2(7) PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL,
    cliente_id NUMBER,
    CONSTRAINT fk_cliente FOREIGN KEY (cliente_id) REFERENCES usuarios(id)
);

Select * from carros;

drop table carros;
drop table usuarios;